'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace Holidays_Custom.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As Holidays_Custom.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Holidays_Custom.Properties.Settings())), Holidays_Custom.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return Holidays_Custom.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
